// app/about-me/my-info/MyInfo.tsx
'use client'

import { usePathname, useRouter, useSearchParams } from 'next/navigation'
import { BookOpen, PenLine } from 'lucide-react'
import { Blog } from '@/components/about/Blog'
import { GitHub } from '@/components/about/GitHub'
import { ReadMore, ReadMoreList } from '@/components/about/ReadMore'
import { useI18n } from '@/components/providers/I18nProvider'
import { BackLink } from '@/components/ui/BackLink'
import { buttonClass } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { Section } from '@/components/ui/Section'
import { Transition } from '@/components/ui/Transition'
import { useData } from '@/lib/data'

const GITHUB_PATH =
  'M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'

const tabs = [
  { key: 'rean', label: 'nav.readMore' },
  { key: 'blog', label: 'nav.blog' },
  { key: 'github', label: 'nav.github' },
] as const

type TabKey = (typeof tabs)[number]['key']

const isTabKey = (value: string | null): value is TabKey => tabs.some(tab => tab.key === value)

/** Profile header, bio, quick facts and social links. */
export function MyInfo() {
  const { personalInfo, socials } = useData()
  const { t } = useI18n()

  const facts = [
    { label: 'Name', value: personalInfo.name },
    { label: 'Role', value: personalInfo.role },
    {
      label: 'Email',
      value: (
        <a href={`mailto:${personalInfo.email}`} className="break-all font-heading underline">
          {personalInfo.email}
        </a>
      ),
    },
    {
      label: 'Phone',
      value: (
        <a href={`tel:${personalInfo.phone.replace(/\s/g, '')}`} className="font-heading underline">
          {personalInfo.phone}
        </a>
      ),
    },
    { label: 'Location', value: personalInfo.location },
  ]

  const connect = [
    { label: 'GitHub', href: personalInfo.github, handle: '@koeuk' },
    { label: 'LinkedIn', href: personalInfo.linkedin, handle: 'koeuk-kos' },
    { label: 'Telegram', href: personalInfo.telegram, handle: '@koeuk24' },
    { label: 'Facebook', href: personalInfo.facebook, handle: '@koeuk25' },
  ]

  return (
    <>
      <header className="reveal mb-12">
        <div className="mb-8">
          <BackLink href="/">{t('nav.home')}</BackLink>
        </div>
        <div className="flex flex-col-reverse gap-8 sm:flex-row sm:items-center sm:justify-between">
          <div className="min-w-0">
            <p className="text-xs font-heading uppercase tracking-widest">{t('nav.myInfo')}</p>
            <h1 className="mt-3 font-heading text-2xl sm:text-4xl">{personalInfo.name}</h1>
            <p className="mt-2 text-lg sm:text-xl">{personalInfo.role}</p>
          </div>
          <img
            src={personalInfo.image}
            alt={personalInfo.name}
            className="neo h-28 w-28 flex-shrink-0 bg-main object-cover sm:h-36 sm:w-36"
          />
        </div>
      </header>

      <Section title={t('nav.about')}>
        <p className="leading-relaxed sm:text-lg">{personalInfo.bio}</p>
      </Section>

      <Section title="Quick Facts">
        <Card as="dl" className="p-0 sm:p-0">
          {facts.map(fact => (
            <div
              key={fact.label}
              className="flex flex-col gap-1 border-b-2 border-border px-4 py-3 last:border-b-0 sm:flex-row sm:items-baseline sm:justify-between sm:gap-6 sm:px-5"
            >
              <dt className="text-xs font-heading uppercase tracking-widest">{fact.label}</dt>
              <dd className="min-w-0 sm:text-right">{fact.value}</dd>
            </div>
          ))}
        </Card>
      </Section>

      <Section title="Connect">
        <div className="flex flex-wrap gap-4">
          {connect.map(link => (
            <a
              key={link.label}
              href={link.href}
              target="_blank"
              rel="noopener noreferrer"
              className="neo neo-press reveal-on-scroll flex min-w-0 items-center gap-3 bg-bw px-4 py-3"
            >
              <svg viewBox="0 0 24 24" className="h-6 w-6 flex-shrink-0" fill="currentColor" aria-hidden="true">
                <path d={socials.find(social => social.href === link.href)?.path} />
              </svg>
              <span className="block min-w-0">
                <span className="block text-xs font-heading uppercase tracking-widest">{link.label}</span>
                <span className="block truncate text-sm">{link.handle}</span>
              </span>
            </a>
          ))}
        </div>
      </Section>
    </>
  )
}

function TabIcon({ tab }: { tab: TabKey }) {
  if (tab === 'rean') return <BookOpen className="h-4 w-4" aria-hidden />
  if (tab === 'blog') return <PenLine className="h-4 w-4" aria-hidden />
  return (
    <svg viewBox="0 0 24 24" className="h-4 w-4" fill="currentColor" aria-hidden="true">
      <path d={GITHUB_PATH} />
    </svg>
  )
}

function TabList({ active, onSelect }: { active: TabKey; onSelect?: (tab: TabKey) => void }) {
  const { t } = useI18n()
  return (
    <div role="tablist" aria-label={t('nav.myInfo')} className="mb-12 flex flex-wrap gap-3">
      {tabs.map(tab => (
        <button
          key={tab.key}
          type="button"
          role="tab"
          id={`my-info-tab-${tab.key}`}
          aria-selected={active === tab.key}
          aria-controls="my-info-panel"
          onClick={() => onSelect?.(tab.key)}
          className={buttonClass(active === tab.key ? 'main' : 'neutral')}
        >
          <TabIcon tab={tab.key} />
          {t(tab.label)}
        </button>
      ))}
    </div>
  )
}

/**
 * Read More / Blog / GitHub tabs. The open tab is the `?section=` query
 * (absent means Read More), replaced in the URL on switch like the Nuxt page.
 * Render inside <Suspense> — it reads the search params.
 */
export function MyInfoTabs() {
  const searchParams = useSearchParams()
  const router = useRouter()
  // Never null under the App Router; the fallbacks only satisfy the types.
  const pathname = usePathname() ?? '/about-me/my-info'
  const section = searchParams?.get('section') ?? null
  const activeTab: TabKey = isTabKey(section) ? section : 'rean'

  const selectTab = (tab: TabKey) => {
    const params = new URLSearchParams(searchParams?.toString())
    if (tab === 'rean') params.delete('section')
    else params.set('section', tab)
    const query = params.toString()
    router.replace(query ? `${pathname}?${query}` : pathname, { scroll: false })
  }

  return (
    <section>
      <TabList active={activeTab} onSelect={selectTab} />
      <Transition name="fade">
        <div key={activeTab} role="tabpanel" id="my-info-panel" aria-labelledby={`my-info-tab-${activeTab}`}>
          {activeTab === 'rean' ? <ReadMore heading /> : activeTab === 'blog' ? <Blog /> : <GitHub />}
        </div>
      </Transition>
    </section>
  )
}

/** Static stand-in for MyInfoTabs until the query can be read: the default Read More tab. */
export function MyInfoTabsFallback() {
  return (
    <section>
      <TabList active="rean" />
      <div role="tabpanel" id="my-info-panel" aria-labelledby="my-info-tab-rean">
        <ReadMoreList heading />
      </div>
    </section>
  )
}

// pages/about-me/my-info/index.vue
<template>
  <div class="min-h-screen pt-32 pb-20 transition-colors">
    <div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Back Link -->
      <NuxtLink to="/"
        class="group inline-flex items-center gap-2 text-sm font-bold text-gray-400 hover:text-primary dark:hover:text-white transition-all uppercase tracking-widest mb-12">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 transition-transform group-hover:-translate-x-1" fill="none"
          viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
        </svg>
        {{ t('nav.home') }}
      </NuxtLink>

      <!-- Header -->
      <div class="grid md:grid-cols-[auto_1fr] gap-10 items-center mb-20">
        <div class="relative w-40 h-40 sm:w-56 sm:h-56 mx-auto md:mx-0">
          <div
            class="absolute inset-0 rounded-full bg-gradient-to-br from-green-500/30 via-blue-500/20 to-emerald-500/30 blur-3xl">
          </div>
          <img :src="personalInfo.image" :alt="personalInfo.name"
            class="relative w-full h-full rounded-full object-cover border-4 border-white dark:border-primary-light shadow-2xl" />
        </div>
        <div class="text-center md:text-left space-y-3">
          <p class="text-sm font-bold text-gray-400 dark:text-gray-500 uppercase tracking-widest">
            {{ t('nav.myInfo') }}
          </p>
          <h1 class="text-5xl md:text-6xl lg:text-7xl font-extrabold text-primary dark:text-white tracking-tight">
            {{ personalInfo.name }}
          </h1>
          <p class="text-xl md:text-2xl text-gray-500 dark:text-gray-400 font-medium">
            {{ personalInfo.role }}
          </p>
        </div>
      </div>

      <!-- Content Grid -->
      <div class="grid lg:grid-cols-3 gap-8">
        <!-- Bio -->
        <section
          class="lg:col-span-2 lg-glass p-8 rounded-3xl border border-gray-200 dark:border-white/10">
          <h2 class="text-sm font-bold text-gray-400 dark:text-gray-500 uppercase tracking-widest mb-6">
            About Me
          </h2>
          <p class="text-lg leading-relaxed text-gray-700 dark:text-gray-300">
            {{ personalInfo.bio }}
          </p>
        </section>

        <!-- Quick Facts -->
        <section
          class="lg-glass p-8 rounded-3xl border border-gray-200 dark:border-white/10">
          <h2 class="text-sm font-bold text-gray-400 dark:text-gray-500 uppercase tracking-widest mb-6">
            Quick Facts
          </h2>
          <dl class="space-y-4">
            <div>
              <dt class="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider mb-1">Name</dt>
              <dd class="text-base font-medium text-primary dark:text-white">{{ personalInfo.name }}</dd>
            </div>
            <div>
              <dt class="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider mb-1">Role</dt>
              <dd class="text-base font-medium text-primary dark:text-white">{{ personalInfo.role }}</dd>
            </div>
            <div>
              <dt class="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider mb-1">Email</dt>
              <dd>
                <a :href="`mailto:${personalInfo.email}`"
                  class="text-base font-medium text-primary dark:text-white hover:underline break-all">
                  {{ personalInfo.email }}
                </a>
              </dd>
            </div>
            <div>
              <dt class="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider mb-1">Phone</dt>
              <dd>
                <a :href="`tel:${personalInfo.phone.replace(/\s/g, '')}`"
                  class="text-base font-medium text-primary dark:text-white hover:underline">
                  {{ personalInfo.phone }}
                </a>
              </dd>
            </div>
            <div>
              <dt class="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider mb-1">Location</dt>
              <dd class="text-base font-medium text-primary dark:text-white">{{ personalInfo.location }}</dd>
            </div>
          </dl>
        </section>

        <!-- Connect / Socials -->
        <section
          class="lg:col-span-3 lg-glass p-8 rounded-3xl border border-gray-200 dark:border-white/10">
          <h2 class="text-sm font-bold text-gray-400 dark:text-gray-500 uppercase tracking-widest mb-6">
            Connect
          </h2>
          <div class="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <a v-for="socialLink in socialLinks" :key="socialLink.label" :href="socialLink.href" target="_blank"
              rel="noopener noreferrer"
              class="lg-glass lg-glass-hover group flex items-center gap-3 p-4 rounded-2xl border border-gray-200 dark:border-white/10">
              <span class="text-2xl">{{ socialLink.icon }}</span>
              <div class="min-w-0">
                <p
                  class="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wider group-hover:text-primary dark:group-hover:text-white transition-colors">
                  {{ socialLink.label }}
                </p>
                <p class="text-sm font-medium text-primary dark:text-white truncate">{{ socialLink.handle }}</p>
              </div>
            </a>
          </div>
        </section>
      </div>
    </div>

    <!-- Tabs -->
    <div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 mt-20">
      <div class="flex justify-center">
        <div role="tablist"
          class="lg-glass inline-flex items-center gap-1 p-1.5 rounded-full border border-gray-300 dark:border-white/15 overflow-x-auto max-w-full">
          <button v-for="tab in tabs" :key="tab.key" role="tab" :aria-selected="activeTab === tab.key"
            @click="activeTab = tab.key"
            class="relative px-5 sm:px-6 py-2.5 text-sm font-semibold rounded-full whitespace-nowrap transition-colors duration-300"
            :class="activeTab === tab.key
              ? 'text-white dark:text-primary'
              : 'text-gray-500 dark:text-gray-400 hover:text-primary dark:hover:text-white'">
            <span class="relative z-10 flex items-center gap-2">
              <span>{{ tab.icon }}</span>
              {{ t(tab.label) }}
            </span>
            <span v-if="activeTab === tab.key"
              class="absolute inset-0 bg-primary dark:bg-white rounded-full -z-0 tab-pill-active"></span>
          </button>
        </div>
      </div>
    </div>

    <!-- Tab Panels -->
    <div class="mt-4">
      <Transition name="tab-fade" mode="out-in">
        <Experience v-if="activeTab === 'projects'" key="projects" />
        <ReadMore v-else-if="activeTab === 'rean'" key="rean" />
        <Blog v-else-if="activeTab === 'blog'" key="blog" />
        <GitHub v-else-if="activeTab === 'github'" key="github" />
      </Transition>
    </div>
  </div>
</template>

<script setup lang="ts">
const { personalInfo } = useData()
const { t } = useI18n()

const socialLinks = [
  { label: 'GitHub', href: personalInfo.github, handle: '@koeuk', icon: '🐙' },
  { label: 'LinkedIn', href: personalInfo.linkedin, handle: 'koeuk-kos', icon: '💼' },
  { label: 'Telegram', href: personalInfo.telegram, handle: '@koeuk24', icon: '✈️' },
  { label: 'Facebook', href: personalInfo.facebook, handle: '@koeuk25', icon: '📘' },
]

const tabs = [
  { key: 'projects', label: 'nav.personalProjects', icon: '🚀' },
  { key: 'rean', label: 'nav.readMore', icon: '📖' },
  { key: 'blog', label: 'nav.blog', icon: '📝' },
  { key: 'github', label: 'nav.github', icon: '🐙' },
] as const

type TabKey = typeof tabs[number]['key']
const validKeys = tabs.map(tab => tab.key) as readonly string[]

const route = useRoute()
const router = useRouter()

const activeTab = computed<TabKey>({
  get: () => {
    const param = route.query.section as string | undefined
    return (param && validKeys.includes(param) ? param : 'projects') as TabKey
  },
  set: (value: TabKey) => {
    const query = { ...route.query }
    if (value === 'projects') {
      delete query.section
    } else {
      query.section = value
    }
    router.replace({ query })
  },
})

useHead({
  title: `My Info | ${personalInfo.name}`,
  meta: [
    { name: 'description', content: personalInfo.bio }
  ]
})
</script>

<style scoped>
.tab-pill-active {
  animation: pillPop 0.4s cubic-bezier(0.22, 1, 0.36, 1);
}

@keyframes pillPop {
  from {
    opacity: 0;
    transform: scale(0.7);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}

.tab-fade-enter-active,
.tab-fade-leave-active {
  transition: all 0.3s cubic-bezier(0.22, 1, 0.36, 1);
}

.tab-fade-enter-from,
.tab-fade-leave-to {
  opacity: 0;
  transform: translateY(8px);
  filter: blur(4px);
}
</style>
