// components/Navbar.vue
<template>
    <nav class="fixed top-0 left-0 right-0 z-[999] transition-all duration-500 ease-out nav-enter px-4 sm:px-6"
        :class="scrolled ? 'pt-3' : 'pt-5'">
        <div class="max-w-7xl mx-auto">
            <div class="flex justify-between items-center gap-3">
                <!-- Logo Pill -->
                <NuxtLink to="/#home"
                    class="group flex items-center gap-2.5 pl-1.5 pr-4 py-1.5 rounded-full bg-white/70 dark:bg-white/5 backdrop-blur-xl border border-black/5 dark:border-white/10 shadow-[0_8px_30px_rgb(0,0,0,0.06)] dark:shadow-[0_8px_30px_rgb(0,0,0,0.3)] hover:scale-[1.02] transition-all duration-300">
                    <img src="/images/profile.jpg" alt="Logo"
                        class="w-9 h-9 rounded-full object-cover ring-2 ring-white dark:ring-white/20 group-hover:ring-primary/30 transition-all" />
                    <span class="text-sm font-semibold text-primary dark:text-white tracking-tight">Koeuk Dev</span>
                </NuxtLink>

                <!-- Desktop Menu Pill -->
                <div
                    class="hidden md:flex items-center gap-1 px-2 py-1.5 rounded-full bg-white/70 dark:bg-white/5 backdrop-blur-xl border border-black/5 dark:border-white/10 shadow-[0_8px_30px_rgb(0,0,0,0.06)] dark:shadow-[0_8px_30px_rgb(0,0,0,0.3)] relative">
                    <NuxtLink v-for="navLink in navLinks" :key="navLink.href" :to="navLink.href"
                        class="relative px-4 py-2 text-sm font-medium rounded-full transition-colors duration-300 z-10"
                        :class="currentActive === navLink.href
                            ? 'text-white dark:text-primary'
                            : 'text-gray-600 dark:text-gray-300 hover:text-primary dark:hover:text-white'">
                        <span class="relative z-10">{{ t(navLink.label) }}</span>
                        <span v-if="currentActive === navLink.href"
                            class="absolute inset-0 bg-primary dark:bg-white rounded-full -z-0 nav-pill-active"></span>
                    </NuxtLink>
                </div>

                <!-- Right Controls Pill -->
                <div
                    class="hidden md:flex items-center gap-2 px-2 py-1.5 rounded-full bg-white/70 dark:bg-white/5 backdrop-blur-xl border border-black/5 dark:border-white/10 shadow-[0_8px_30px_rgb(0,0,0,0.06)] dark:shadow-[0_8px_30px_rgb(0,0,0,0.3)]">
                    <!-- Language Selector -->
                    <div class="relative">
                        <button @click.stop="showLanguageMenu = !showLanguageMenu"
                            class="flex items-center gap-1.5 px-3 py-1.5 rounded-full hover:bg-black/5 dark:hover:bg-white/10 transition-colors text-sm">
                            <span class="text-base leading-none">{{ currentFlag }}</span>
                            <svg class="w-3.5 h-3.5 text-gray-500 dark:text-gray-400 transition-transform duration-300"
                                :class="{ 'rotate-180': showLanguageMenu }" fill="none" stroke="currentColor"
                                viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5"
                                    d="M19 9l-7 7-7-7" />
                            </svg>
                        </button>
                        <Transition name="dropdown">
                            <div v-if="showLanguageMenu"
                                class="absolute right-0 mt-3 w-40 bg-white/90 dark:bg-primary/95 backdrop-blur-xl rounded-2xl shadow-xl border border-black/5 dark:border-white/10 overflow-hidden p-1.5">
                                <button v-for="language in languages" :key="language.code"
                                    @click="selectLanguage(language.code as 'en' | 'km' | 'zh')"
                                    class="w-full px-3 py-2 text-left rounded-xl flex items-center gap-2.5 text-sm transition-colors"
                                    :class="currentLang === language.code
                                        ? 'bg-primary/10 dark:bg-white/10 text-primary dark:text-white font-medium'
                                        : 'text-gray-700 dark:text-gray-200 hover:bg-black/5 dark:hover:bg-white/5'">
                                    <span class="text-base">{{ language.flag }}</span>
                                    <span>{{ language.name }}</span>
                                </button>
                            </div>
                        </Transition>
                    </div>

                    <!-- Divider -->
                    <span class="w-px h-5 bg-black/10 dark:bg-white/10"></span>

                    <!-- Theme Toggle Switch -->
                    <button @click="toggleTheme" class="toggle-switch" :class="{ 'active': isDark }"
                        aria-label="Toggle theme">
                        <span class="toggle-slider">
                            <svg v-if="!isDark" class="w-3 h-3 text-amber-500" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd"
                                    d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z"
                                    clip-rule="evenodd" />
                            </svg>
                            <svg v-else class="w-3 h-3 text-indigo-300" fill="currentColor" viewBox="0 0 20 20">
                                <path
                                    d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z" />
                            </svg>
                        </span>
                    </button>
                </div>

                <!-- Mobile Menu Button -->
                <div
                    class="flex items-center gap-1 md:hidden px-2 py-1.5 rounded-full bg-white/70 dark:bg-white/5 backdrop-blur-xl border border-black/5 dark:border-white/10 shadow-[0_8px_30px_rgb(0,0,0,0.06)] dark:shadow-[0_8px_30px_rgb(0,0,0,0.3)]">
                    <button @click="toggleTheme" class="toggle-switch" :class="{ 'active': isDark }"
                        aria-label="Toggle theme">
                        <span class="toggle-slider"></span>
                    </button>
                    <button @click="isOpen = !isOpen"
                        class="p-2 rounded-full hover:bg-black/5 dark:hover:bg-white/10 text-gray-700 dark:text-white transition-colors"
                        aria-label="Toggle menu">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path v-if="isOpen" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5"
                                d="M6 18L18 6M6 6l12 12" />
                            <path v-else stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5"
                                d="M4 7h16M4 12h16M4 17h16" />
                        </svg>
                    </button>
                </div>
            </div>
        </div>

        <!-- Mobile Menu -->
        <Transition name="mobile-menu">
            <div v-if="isOpen" class="md:hidden mt-3 max-w-7xl mx-auto">
                <div
                    class="bg-white/80 dark:bg-primary/90 backdrop-blur-xl rounded-3xl border border-black/5 dark:border-white/10 shadow-2xl overflow-hidden p-2">
                    <NuxtLink v-for="navLink in navLinks" :key="navLink.href" :to="navLink.href" @click="isOpen = false"
                        class="block px-4 py-3 rounded-2xl transition-all text-sm font-medium"
                        :class="currentActive === navLink.href
                            ? 'bg-primary text-white dark:bg-white dark:text-primary'
                            : 'text-gray-700 dark:text-gray-200 hover:bg-black/5 dark:hover:bg-white/10'">
                        {{ t(navLink.label) }}
                    </NuxtLink>
                    <div class="mt-2 pt-2 border-t border-black/5 dark:border-white/10 px-1">
                        <div class="flex gap-1.5 p-1">
                            <button v-for="language in languages" :key="language.code"
                                @click="selectLanguage(language.code as 'en' | 'km' | 'zh')"
                                class="flex-1 py-2 rounded-xl text-center text-sm font-medium transition-all"
                                :class="currentLang === language.code
                                    ? 'bg-primary text-white dark:bg-white dark:text-primary'
                                    : 'bg-black/5 dark:bg-white/5 text-gray-700 dark:text-gray-200'">
                                {{ language.flag }} {{ language.name }}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </Transition>
    </nav>
</template>

<script setup lang="ts">
    const { isDark, toggleTheme, initTheme } = useTheme()
    const { t, currentLang, setLanguage, languages } = useI18n()

    const route = useRoute()
    const isOpen = ref(false)
    const scrolled = ref(false)
    const showLanguageMenu = ref(false)
    const activeSection = ref('/#home')

    const isHomePage = computed(() => route.path === '/')
    const currentActive = computed(() => {
        if (!isHomePage.value) {
            const match = navLinks.find(navLink => route.path.startsWith(navLink.href.replace('/#', '/')) && !navLink.href.startsWith('/#'))
            return match?.href || ''
        }
        return activeSection.value
    })

    const navLinks = [
        { href: '/#home', label: 'nav.home' },
        { href: '/#skills', label: 'nav.skills' },
        { href: '/#github', label: 'nav.github' },
        { href: '/#personal-projects', label: 'nav.personalProjects' },
        { href: '/#work-experience', label: 'nav.workExperience' },
        { href: '/#about', label: 'nav.about' },
        { href: '/#contact', label: 'nav.contact' },
        { href: '/blog', label: 'nav.blog', isPage: true }
    ]

    const currentFlag = computed(() => {
        const language = languages.find(language => language.code === currentLang.value)
        return language?.flag || '🇺🇸'
    })

    const selectLanguage = (language: 'en' | 'km' | 'zh') => {
        setLanguage(language)
        showLanguageMenu.value = false
    }

    onMounted(() => {
        initTheme()
        window.addEventListener('scroll', handleScroll)
        document.addEventListener('click', closeLanguageMenu)
    })

    onUnmounted(() => {
        window.removeEventListener('scroll', handleScroll)
        document.removeEventListener('click', closeLanguageMenu)
    })

    function handleScroll() {
        scrolled.value = window.scrollY > 20

        if (window.innerHeight + window.scrollY >= document.body.scrollHeight - 100) {
            activeSection.value = '/#contact'
            return
        }

        const sections = ['home', 'skills', 'github', 'personal-projects', 'work-experience', 'about', 'contact']
        const scrollPosition = window.scrollY + 150

        for (let index = sections.length - 1; index >= 0; index--) {
            const element = document.getElementById(sections[index])
            if (element && element.offsetTop <= scrollPosition) {
                activeSection.value = `/#${sections[index]}`
                return
            }
        }
        activeSection.value = '/#home'
    }

    function closeLanguageMenu(event: Event) {
        const target = event.target as HTMLElement
        if (!target.closest('.relative')) {
            showLanguageMenu.value = false
        }
    }
</script>

<style scoped>
.nav-enter {
    animation: navSlideDown 1s cubic-bezier(0.22, 1, 0.36, 1) forwards;
}

@keyframes navSlideDown {
    from {
        opacity: 0;
        filter: blur(10px);
        transform: translateY(-20px);
    }
    to {
        opacity: 1;
        filter: blur(0);
        transform: translateY(0);
    }
}

.nav-pill-active {
    animation: pillPop 0.4s cubic-bezier(0.22, 1, 0.36, 1);
}

@keyframes pillPop {
    from {
        opacity: 0;
        transform: scale(0.7);
    }
    to {
        opacity: 1;
        transform: scale(1);
    }
}

.mobile-menu-enter-active {
    transition: all 0.5s cubic-bezier(0.22, 1, 0.36, 1);
}

.mobile-menu-leave-active {
    transition: all 0.3s cubic-bezier(0.22, 1, 0.36, 1);
}

.mobile-menu-enter-from,
.mobile-menu-leave-to {
    opacity: 0;
    filter: blur(4px);
    transform: translateY(-10px);
}

.dropdown-enter-active {
    transition: all 0.4s cubic-bezier(0.22, 1, 0.36, 1);
}

.dropdown-leave-active {
    transition: all 0.25s cubic-bezier(0.22, 1, 0.36, 1);
}

.dropdown-enter-from,
.dropdown-leave-to {
    opacity: 0;
    filter: blur(4px);
    transform: translateY(-8px) scale(0.9);
}

/* Theme Toggle Switch */
.toggle-switch {
    position: relative;
    width: 44px;
    height: 24px;
    background: #e5e7eb;
    border-radius: 9999px;
    border: none;
    cursor: pointer;
    transition: background 0.3s ease;
    flex-shrink: 0;
}

.toggle-switch.active {
    background: #1a1a1a;
}

.toggle-slider {
    position: absolute;
    top: 2px;
    left: 2px;
    width: 20px;
    height: 20px;
    background: white;
    border-radius: 50%;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    transition: transform 0.3s cubic-bezier(0.68, -0.55, 0.265, 1.55);
    display: flex;
    align-items: center;
    justify-content: center;
}

.toggle-switch.active .toggle-slider {
    transform: translateX(20px);
    background: #ffffff;
}
</style>

// components/layout/Navbar.tsx
'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useEffect, useState } from 'react'
import { Menu, Moon, Sun, X } from 'lucide-react'
import { useI18n } from '@/components/providers/I18nProvider'
import { useTheme } from '@/components/providers/ThemeProvider'
import { cn } from '@/lib/utils'

const navLinks = [
  { href: '/', section: 'home', label: 'nav.home' },
  { href: '/#skills', section: 'skills', label: 'nav.skills' },
  { href: '/#personal-projects', section: 'personal-projects', label: 'nav.personalProjects' },
  { href: '/#work-experience', section: 'work-experience', label: 'nav.workExperience' },
  { href: '/#about', section: 'about', label: 'nav.about' },
]

/** Which home-page section is under the navbar, for the active pill. */
function useActiveSection(enabled: boolean) {
  const [active, setActive] = useState('home')

  useEffect(() => {
    if (!enabled) return

    const onScroll = () => {
      if (window.innerHeight + window.scrollY >= document.body.scrollHeight - 100) {
        setActive('about')
        return
      }
      const position = window.scrollY + 150
      for (let index = navLinks.length - 1; index > 0; index--) {
        const element = document.getElementById(navLinks[index].section)
        if (element && element.offsetTop <= position) {
          setActive(navLinks[index].section)
          return
        }
      }
      setActive('home')
    }

    onScroll()
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [enabled])

  return active
}

export function Navbar() {
  const pathname = usePathname()
  const { t, currentLang, setLanguage, languages } = useI18n()
  const { isDark, toggleTheme } = useTheme()
  const [menuOpen, setMenuOpen] = useState(false)

  const isHome = pathname === '/'
  const activeSection = useActiveSection(isHome)

  useEffect(() => setMenuOpen(false), [pathname])

  const isActive = (section: string) => isHome && activeSection === section

  // Two languages are enabled, so the switch is a single toggle showing the next one.
  const nextLanguage = languages[(languages.findIndex(language => language.code === currentLang) + 1) % languages.length]

  const linkClass = (section: string) =>
    cn(
      'rounded-base border-2 px-2 py-1 transition-colors hover:border-border',
      isActive(section) ? 'border-border' : 'border-transparent',
    )

  const controls = (
    <>
      <button
        type="button"
        onClick={() => setLanguage(nextLanguage.code)}
        className="rounded-base border-2 border-transparent px-2 py-1 font-heading transition-colors hover:border-border"
        aria-label={`${t('common.language')}: ${nextLanguage.name}`}
      >
        {nextLanguage.code.toUpperCase()}
      </button>
      <button type="button" onClick={toggleTheme} aria-label={t('common.theme')} className="px-1">
        {isDark ? <Sun className="h-5 w-5 sm:h-6 sm:w-6" /> : <Moon className="h-5 w-5 sm:h-6 sm:w-6" />}
      </button>
    </>
  )

  return (
    <div className="fixed left-0 top-5 z-50 w-full px-5">
      <nav className="neo mx-auto flex w-full items-center gap-4 bg-main p-2.5 px-5 text-sm font-base text-main-fg sm:text-base md:w-max md:max-w-full lg:gap-5">
        {/* Desktop: every link in the pill */}
        <div className="hidden items-center gap-3 md:flex lg:gap-5">
          {navLinks.map(link => (
            <Link key={link.href} href={link.href} className={linkClass(link.section)}>
              {t(link.label)}
            </Link>
          ))}
        </div>

        {/* Mobile: brand + menu toggle */}
        <Link href="/" className="mr-auto font-heading md:hidden">
          Koeuk
        </Link>

        <div className="flex items-center gap-2 sm:gap-3">{controls}</div>

        <button
          type="button"
          className="md:hidden"
          onClick={() => setMenuOpen(open => !open)}
          aria-expanded={menuOpen}
          aria-label={menuOpen ? t('common.close') : t('common.menu')}
        >
          {menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
        </button>
      </nav>

      {menuOpen && (
        <div className="neo mx-auto mt-3 flex flex-col gap-1 bg-main p-3 text-main-fg md:hidden">
          {navLinks.map(link => (
            <Link key={link.href} href={link.href} onClick={() => setMenuOpen(false)} className={linkClass(link.section)}>
              {t(link.label)}
            </Link>
          ))}
        </div>
      )}
    </div>
  )
}
