// components/home/About.tsx
'use client'

import { Download, UserRound } from 'lucide-react'
import { useI18n } from '@/components/providers/I18nProvider'
import { Button } from '@/components/ui/Button'
import { Section } from '@/components/ui/Section'
import { Tag } from '@/components/ui/Tag'
import { useData } from '@/lib/data'

const badgeKeys = [
  'badge.frontend',
  'badge.responsive',
  'badge.typescript',
  'badge.frameworks',
  'badge.uiux',
  'badge.problemSolving',
]

export function About() {
  const { personalInfo } = useData()
  const { t } = useI18n()

  return (
    <Section id="about" title={t('about.title')} className="mb-0">
      <div className="flex flex-col gap-8 sm:flex-row sm:items-start">
        <img
          src="/images/koeuk.jpg"
          alt={personalInfo.name}
          className="neo h-40 w-40 flex-shrink-0 bg-main object-cover"
          loading="lazy"
        />
        <div>
          <p className="leading-relaxed sm:text-lg">{t('about.bio')}</p>

          <h3 className="mb-3 mt-8 font-heading">{t('about.keySkills')}</h3>
          <div className="flex flex-wrap gap-2">
            {badgeKeys.map(badge => (
              <Tag key={badge}>{t(badge)}</Tag>
            ))}
          </div>

          <div className="mt-8 flex flex-wrap gap-4">
            <Button href="/about-me/my-info" variant="main">
              <UserRound className="h-4 w-4" />
              {t('nav.myInfo')}
            </Button>
            <Button href="/resume.pdf">
              <Download className="h-4 w-4" />
              {t('about.downloadResume')}
            </Button>
          </div>
        </div>
      </div>
    </Section>
  )
}

// components/About.vue
<template>
    <section id="about" class="section dark:bg-primary">
        <div class="grid md:grid-cols-2 gap-12 items-center">
            <!-- Photo with Avatar -->
            <div class="flex justify-center">
                <Avatar class="w-80 h-80 shadow-2xl border-4 border-accent/20">
                    <AvatarImage src="/images/koeuk.jpg" :alt="personalInfo.name" />
                    <AvatarFallback
                        class="bg-gradient-to-br from-primary to-primary-light text-white text-6xl font-bold">
                        {{personalInfo.name.split(' ').map(n => n[0]).join('')}}
                    </AvatarFallback>
                </Avatar>
            </div>

            <!-- Content -->
            <div>
                <h2 class="text-4xl md:text-5xl font-bold mb-6 text-primary dark:text-white">
                    {{ t('about.title') }}
                </h2>
                <p class="text-gray-700 dark:text-gray-300 text-lg leading-relaxed mb-8">
                    {{ t('about.bio') }}
                </p>

                <h3 class="text-2xl font-bold mb-4 text-primary dark:text-white">
                    {{ t('about.keySkills') }}
                </h3>
                <div class="flex flex-wrap gap-3 mb-8">
                    <span v-for="badge in badgeKeys" :key="badge"
                        class="px-4 py-2 bg-accent/10 text-accent font-medium rounded-full text-sm">
                        {{ t(badge) }}
                    </span>
                </div>

                <Button variant="outline" size="lg" as="a" href="/resume.pdf" download
                    class="border-accent text-accent hover:bg-accent hover:text-primary dark:border-accent dark:text-accent">
                    <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    {{ t('about.downloadResume') }}
                </Button>
            </div>
        </div>
    </section>
</template>

<script setup lang="ts">
    const { personalInfo } = useData()
    const { t } = useI18n()

    const badgeKeys = [
        'badge.frontend',
        'badge.responsive',
        'badge.typescript',
        'badge.frameworks',
        'badge.uiux',
        'badge.problemSolving'
    ]
</script>
