// app/hotel-booking/HotelBooking.tsx
'use client'

import { useCallback, useState } from 'react'
import { useI18n } from '@/components/providers/I18nProvider'
import { Card } from '@/components/ui/Card'
import { Container } from '@/components/ui/Container'
import { ScreenshotGrid, type GalleryImage } from '@/components/ui/Gallery'
import { Lightbox } from '@/components/ui/Lightbox'
import { PageHeader } from '@/components/ui/PageHeader'
import { Section } from '@/components/ui/Section'
import { Tag } from '@/components/ui/Tag'

const shot = (imageNumber: number): GalleryImage => ({
  src: `/images/hotel-booking/${imageNumber}.png`,
  alt: `Hotel Booking Screenshot ${imageNumber}`,
})

const webUserNumbers = [25, 26, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
const adminNumbers = Array.from({ length: 36 }, (_, index) => index + 4).filter(
  index => ![11, 18].includes(index) && !webUserNumbers.includes(index),
)
const webUserShots = webUserNumbers.map(shot)
const adminShots = adminNumbers.map(shot)
// One lightbox steps through both galleries.
const allShots = [...webUserShots, ...adminShots]

const techStack = [
  'Laravel 12',
  'React 18',
  'Inertia.js',
  'Tailwind CSS',
  'Shadcn UI',
  'MySQL',
  'Sanctum',
  'Vite',
  'Recharts',
  'Leaflet',
]

const stats = [
  { value: '34', label: 'API Endpoints' },
  { value: '12', label: 'DB Tables' },
  { value: '35', label: 'Screenshots' },
  { value: '2', label: 'User Roles' },
]

const features = [
  { icon: '🏨', title: 'Hotel Browsing', description: 'Search and filter hotels by city, country, or keyword with real-time results.' },
  { icon: '🗓', title: 'Room Availability', description: 'Real-time overlap detection for check-in/check-out dates with auto-calculated pricing.' },
  { icon: '💳', title: 'Payment Processing', description: 'Support for Card, Cash, and PayPal methods with full transaction tracking.' },
  { icon: '🎫', title: 'Coupon System', description: 'Percentage-based discount codes with date validity and usage limits.' },
  { icon: '⭐', title: 'Reviews & Ratings', description: 'Rate hotels 1-5 stars after completed bookings with moderation tools.' },
  { icon: '📊', title: 'Admin Dashboard', description: 'Analytics with weekly/monthly/yearly breakdowns, PDF and Excel export.' },
  { icon: '🔐', title: 'Authentication', description: 'Laravel Sanctum + Breeze with Google and Facebook OAuth social login.' },
  { icon: '🔔', title: 'Notifications', description: 'Multi-channel alerts via email, in-app database, and Telegram bot.' },
  { icon: '🗺', title: 'Maps Integration', description: 'Hotel location maps with Leaflet and OpenStreetMap, no API key required.' },
  { icon: '🌙', title: 'Dark Mode', description: 'Persistent theme toggle with system preference detection.' },
]

const tables = [
  'users',
  'hotels',
  'room_types',
  'rooms',
  'bookings',
  'payments',
  'reviews',
  'amenities',
  'hotel_amenities',
  'coupons',
  'settings',
  'notifications',
]

const httpMethods = ['GET', 'POST', 'PUT', 'DELETE']

const integrations = [
  { icon: '🔵', name: 'Google OAuth', description: 'Social login via Google' },
  { icon: '🔷', name: 'Facebook OAuth', description: 'Social login via Facebook' },
  { icon: '✈️', name: 'Telegram Bot', description: 'Admin booking alerts' },
  { icon: '📧', name: 'SMTP Email', description: 'Booking notifications' },
  { icon: '🗺', name: 'OpenStreetMap', description: 'Hotel location maps' },
  { icon: '📄', name: 'PDF/Excel Export', description: 'jsPDF + SheetJS reports' },
]

export function HotelBooking() {
  const { t } = useI18n()
  const [lightboxIndex, setLightboxIndex] = useState<number | null>(null)
  const closeLightbox = useCallback(() => setLightboxIndex(null), [])

  return (
    <Container wide className="[&>*:last-child]:mb-0">
      <PageHeader
        backHref="/#personal-projects"
        title="Hotel Booking"
        subtitle="Hotel Booking System"
        actions={
          <span className="rounded-base border-2 border-border px-3 py-1.5 font-heading text-sm">2025 - 2026</span>
        }
      />

      <div className="mb-12 flex flex-wrap gap-3">
        {techStack.map(technology => (
          <Tag key={technology} className="px-3 py-1 text-sm">
            {technology}
          </Tag>
        ))}
      </div>

      <dl className="neo mb-16 grid grid-cols-2 gap-[2px] overflow-hidden bg-border sm:grid-cols-4">
        {stats.map(stat => (
          <div key={stat.label} className="flex flex-col-reverse bg-main p-4 text-center text-main-fg sm:p-5">
            <dt className="text-sm">{stat.label}</dt>
            <dd className="font-heading text-2xl sm:text-3xl">{stat.value}</dd>
          </div>
        ))}
      </dl>

      <Section title="Features">
        <div className="grid gap-5 sm:grid-cols-2">
          {features.map(feature => (
            <Card key={feature.title}>
              <span
                className="flex h-10 w-10 items-center justify-center rounded-base border-2 border-border bg-main text-lg"
                aria-hidden="true"
              >
                {feature.icon}
              </span>
              <h3 className="mt-4 font-heading text-lg sm:text-xl">{feature.title}</h3>
              <p className="mt-2 leading-relaxed">{feature.description}</p>
            </Card>
          ))}
        </div>
      </Section>

      <Section title="Database Schema">
        <ul className="flex flex-wrap gap-3">
          {tables.map(table => (
            <li key={table} className="rounded-base border-2 border-border bg-bw px-3 py-1.5 font-mono text-sm">
              {table}
            </li>
          ))}
        </ul>
      </Section>

      <Card as="section" tone="main" className="mb-16" aria-labelledby="hotel-api">
        <div className="flex items-center gap-3">
          <Tag>REST API</Tag>
          <span className="text-sm">v1</span>
        </div>
        <h2 id="hotel-api" className="mt-3 font-heading text-xl sm:text-2xl">
          34 API Endpoints
        </h2>
        <p className="mt-2 leading-relaxed">
          Authentication, Hotels, Rooms, Bookings, Payments, Reviews, Coupons, Notifications, Profile
        </p>
        <div className="mt-4 flex flex-wrap gap-2">
          {httpMethods.map(method => (
            <Tag key={method} className="font-mono">
              {method}
            </Tag>
          ))}
        </div>
      </Card>

      <Section title="Screenshots — Web User">
        <ScreenshotGrid images={webUserShots} onOpen={index => setLightboxIndex(index)} />
      </Section>

      <Section title="Screenshots — Admin">
        <ScreenshotGrid images={adminShots} onOpen={index => setLightboxIndex(webUserShots.length + index)} />
      </Section>

      <Section title={t('hotel.integrations')}>
        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {integrations.map(integration => (
            <Card key={integration.name} className="flex items-center gap-4">
              <span className="text-2xl" aria-hidden="true">
                {integration.icon}
              </span>
              <div>
                <p className="font-heading">{integration.name}</p>
                <p className="text-sm">{integration.description}</p>
              </div>
            </Card>
          ))}
        </div>
      </Section>

      <Lightbox images={allShots} index={lightboxIndex} onIndexChange={setLightboxIndex} onClose={closeLightbox} />
    </Container>
  )
}

// pages/hotel-booking/index.vue
<template>
  <div class="min-h-screen bg-[#0a0a0a] text-white">
    <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-20">
      <!-- Header -->
      <div class="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-20 space-y-4">
        <div class="space-y-4">
          <NuxtLink to="/experience" class="group inline-flex items-center gap-2 text-sm font-bold text-gray-400 hover:text-white transition-all uppercase tracking-widest translate-x-0 hover:-translate-x-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Back to Experience
          </NuxtLink>
          <div class="space-y-2 pt-4">
            <h1 class="text-4xl md:text-5xl lg:text-7xl font-extrabold text-white">
              Hotel Booking
            </h1>
            <p class="text-2xl md:text-3xl font-medium text-gray-400">
              Hotel Booking System
            </p>
          </div>
        </div>
        <div class="px-6 py-2 rounded-full border border-gray-700 font-bold text-white uppercase tracking-widest text-sm whitespace-nowrap">
          2025 - 2026
        </div>
      </div>

      <!-- Tech Stack Pills -->
      <div class="flex flex-wrap gap-3 mb-16">
        <span v-for="technology in techStack" :key="technology.name"
          class="px-4 py-2 rounded-full text-sm font-medium border"
          :class="technology.color">
          {{ technology.name }}
        </span>
      </div>

      <!-- Overview Cards -->
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-16">
        <div v-for="stat in stats" :key="stat.label"
          class="p-5 rounded-2xl bg-white/5 border border-white/10 text-center">
          <p class="text-3xl font-bold text-white mb-1">{{ stat.value }}</p>
          <p class="text-sm text-gray-400">{{ stat.label }}</p>
        </div>
      </div>

      <!-- Features Section -->
      <div class="mb-16">
        <h2 class="text-3xl font-bold mb-8">Features</h2>
        <div class="grid md:grid-cols-2 gap-6">
          <div v-for="feature in features" :key="feature.title"
            class="p-6 rounded-2xl bg-white/5 border border-white/10 hover:border-green-500/30 transition-all group">
            <div class="w-10 h-10 rounded-xl mb-4 flex items-center justify-center text-lg"
              :class="feature.iconBg">
              {{ feature.icon }}
            </div>
            <h3 class="text-lg font-semibold mb-2 group-hover:text-green-300 transition-colors">{{ feature.title }}</h3>
            <p class="text-sm text-gray-400 leading-relaxed">{{ feature.description }}</p>
          </div>
        </div>
      </div>

      <!-- Database Schema -->
      <div class="mb-16">
        <h2 class="text-3xl font-bold mb-8">Database Schema</h2>
        <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">
          <div v-for="table in tables" :key="table"
            class="px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-sm font-mono text-gray-300 hover:border-blue-500/40 hover:text-blue-300 transition-all">
            {{ table }}
          </div>
        </div>
      </div>

      <!-- API Section -->
      <div class="mb-16 p-6 rounded-2xl bg-gradient-to-r from-green-900/20 to-blue-900/20 border border-white/10">
        <div class="flex items-center gap-3 mb-3">
          <span class="px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-400 text-xs font-bold">REST API</span>
          <span class="text-gray-400 text-sm">v1</span>
        </div>
        <h3 class="text-2xl font-bold mb-2">34 API Endpoints</h3>
        <p class="text-gray-400 mb-4">Authentication, Hotels, Rooms, Bookings, Payments, Reviews, Coupons, Notifications, Profile</p>
        <div class="flex flex-wrap gap-2">
          <span class="px-3 py-1 rounded-full bg-green-500/20 text-green-400 text-xs font-mono">GET</span>
          <span class="px-3 py-1 rounded-full bg-blue-500/20 text-blue-400 text-xs font-mono">POST</span>
          <span class="px-3 py-1 rounded-full bg-yellow-500/20 text-yellow-400 text-xs font-mono">PUT</span>
          <span class="px-3 py-1 rounded-full bg-red-500/20 text-red-400 text-xs font-mono">DELETE</span>
        </div>
      </div>

      <!-- Screenshots Gallery - Web User -->
      <div class="mb-16">
        <h2 class="text-3xl font-bold mb-8">Screenshots — Web User</h2>
        <div class="columns-1 md:columns-2 gap-4 space-y-4">
          <div v-for="imageNumber in webUserImages" :key="imageNumber"
            class="break-inside-avoid rounded-xl overflow-hidden transition-all cursor-pointer group"
            @click="openLightbox(imageNumber)">
            <img
              :src="`/images/hotel-booking/${imageNumber}.png`"
              :alt="`Hotel Booking Screenshot ${imageNumber}`"
              class="w-full block group-hover:scale-[1.02] transition-transform duration-500"
              loading="lazy"
            />
          </div>
        </div>
      </div>

      <!-- Screenshots Gallery - Admin -->
      <div class="mb-16">
        <h2 class="text-3xl font-bold mb-8">Screenshots — Admin</h2>
        <div class="columns-1 md:columns-2 gap-4 space-y-4">
          <div v-for="imageNumber in adminImages" :key="imageNumber"
            class="break-inside-avoid rounded-xl overflow-hidden transition-all cursor-pointer group"
            @click="openLightbox(imageNumber)">
            <img
              :src="`/images/hotel-booking/${imageNumber}.png`"
              :alt="`Hotel Booking Screenshot ${imageNumber}`"
              class="w-full block group-hover:scale-[1.02] transition-transform duration-500"
              loading="lazy"
            />
          </div>
        </div>
      </div>

      <!-- Integrations -->
      <div class="mb-16">
        <h2 class="text-3xl font-bold mb-8">{{ t('hotel.integrations') }}</h2>
        <div class="grid sm:grid-cols-2 md:grid-cols-3 gap-4">
          <div v-for="integration in integrations" :key="integration.name"
            class="flex items-center gap-4 p-4 rounded-xl bg-white/5 border border-white/10">
            <span class="text-2xl">{{ integration.icon }}</span>
            <div>
              <p class="font-semibold text-sm">{{ integration.name }}</p>
              <p class="text-xs text-gray-400">{{ integration.description }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Lightbox -->
    <Teleport to="body">
      <Transition name="lightbox">
        <div v-if="lightboxImage" class="fixed inset-0 z-[9999] bg-black/95 flex items-center justify-center p-4"
          @click.self="lightboxImage = null">
          <button @click="lightboxImage = null"
            class="absolute top-6 right-6 w-10 h-10 rounded-full bg-white/10 flex items-center justify-center text-white hover:bg-white/20 transition-colors">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
          <button @click="previousImage" class="absolute left-4 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-white/10 flex items-center justify-center text-white hover:bg-white/20 transition-colors">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
          </button>
          <img :src="`/images/hotel-booking/${lightboxImage}.png`" alt="" class="max-h-[90vh] max-w-[90vw] rounded-xl shadow-2xl" />
          <button @click="nextImage" class="absolute right-4 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-white/10 flex items-center justify-center text-white hover:bg-white/20 transition-colors">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
            </svg>
          </button>
          <p class="absolute bottom-6 left-1/2 -translate-x-1/2 text-gray-400 text-sm">{{ imageIndices.indexOf(lightboxImage!) + 1 }} / {{ imageIndices.length }}</p>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
useHead({ title: 'Hotel Booking System - Koeuk Dev' })
const { t } = useI18n()

const webUserImages = [25, 26, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
const adminImages = Array.from({ length: 36 }, (_, index) => index + 4).filter(index => ![11, 18].includes(index) && !webUserImages.includes(index))
const imageIndices = [...webUserImages, ...adminImages]
const lightboxImage = ref<number | null>(null)

function openLightbox(imageNumber: number) { lightboxImage.value = imageNumber }
function nextImage() {
  if (!lightboxImage.value) return
  const index = imageIndices.indexOf(lightboxImage.value)
  lightboxImage.value = imageIndices[(index + 1) % imageIndices.length]
}
function previousImage() {
  if (!lightboxImage.value) return
  const index = imageIndices.indexOf(lightboxImage.value)
  lightboxImage.value = imageIndices[(index - 1 + imageIndices.length) % imageIndices.length]
}

onMounted(() => {
  document.addEventListener('keydown', (event) => {
    if (!lightboxImage.value) return
    if (event.key === 'Escape') lightboxImage.value = null
    if (event.key === 'ArrowRight') nextImage()
    if (event.key === 'ArrowLeft') previousImage()
  })
})

const techStack = [
  { name: 'Laravel 12', color: 'bg-red-500/10 border-red-500/30 text-red-400' },
  { name: 'React 18', color: 'bg-cyan-500/10 border-cyan-500/30 text-cyan-400' },
  { name: 'Inertia.js', color: 'bg-green-500/10 border-green-500/30 text-green-400' },
  { name: 'Tailwind CSS', color: 'bg-sky-500/10 border-sky-500/30 text-sky-400' },
  { name: 'Shadcn UI', color: 'bg-white/10 border-white/20 text-gray-300' },
  { name: 'MySQL', color: 'bg-blue-500/10 border-blue-500/30 text-blue-400' },
  { name: 'Sanctum', color: 'bg-orange-500/10 border-orange-500/30 text-orange-400' },
  { name: 'Vite', color: 'bg-green-500/10 border-green-500/30 text-green-400' },
  { name: 'Recharts', color: 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400' },
  { name: 'Leaflet', color: 'bg-green-500/10 border-green-500/30 text-green-400' },
]

const stats = [
  { value: '34', label: 'API Endpoints' },
  { value: '12', label: 'DB Tables' },
  { value: '35', label: 'Screenshots' },
  { value: '2', label: 'User Roles' },
]

const features = [
  { icon: '🏨', title: 'Hotel Browsing', description: 'Search and filter hotels by city, country, or keyword with real-time results.', iconBg: 'bg-green-500/20' },
  { icon: '🗓', title: 'Room Availability', description: 'Real-time overlap detection for check-in/check-out dates with auto-calculated pricing.', iconBg: 'bg-blue-500/20' },
  { icon: '💳', title: 'Payment Processing', description: 'Support for Card, Cash, and PayPal methods with full transaction tracking.', iconBg: 'bg-emerald-500/20' },
  { icon: '🎫', title: 'Coupon System', description: 'Percentage-based discount codes with date validity and usage limits.', iconBg: 'bg-yellow-500/20' },
  { icon: '⭐', title: 'Reviews & Ratings', description: 'Rate hotels 1-5 stars after completed bookings with moderation tools.', iconBg: 'bg-orange-500/20' },
  { icon: '📊', title: 'Admin Dashboard', description: 'Analytics with weekly/monthly/yearly breakdowns, PDF and Excel export.', iconBg: 'bg-pink-500/20' },
  { icon: '🔐', title: 'Authentication', description: 'Laravel Sanctum + Breeze with Google and Facebook OAuth social login.', iconBg: 'bg-red-500/20' },
  { icon: '🔔', title: 'Notifications', description: 'Multi-channel alerts via email, in-app database, and Telegram bot.', iconBg: 'bg-cyan-500/20' },
  { icon: '🗺', title: 'Maps Integration', description: 'Hotel location maps with Leaflet and OpenStreetMap, no API key required.', iconBg: 'bg-green-500/20' },
  { icon: '🌙', title: 'Dark Mode', description: 'Persistent theme toggle with system preference detection.', iconBg: 'bg-gray-500/20' },
]

const tables = [
  'users', 'hotels', 'room_types', 'rooms', 'bookings', 'payments',
  'reviews', 'amenities', 'hotel_amenities', 'coupons', 'settings', 'notifications'
]

const integrations = [
  { icon: '🔵', name: 'Google OAuth', description: 'Social login via Google' },
  { icon: '🔷', name: 'Facebook OAuth', description: 'Social login via Facebook' },
  { icon: '✈️', name: 'Telegram Bot', description: 'Admin booking alerts' },
  { icon: '📧', name: 'SMTP Email', description: 'Booking notifications' },
  { icon: '🗺', name: 'OpenStreetMap', description: 'Hotel location maps' },
  { icon: '📄', name: 'PDF/Excel Export', description: 'jsPDF + SheetJS reports' },
]
</script>

<style scoped>
.lightbox-enter-active { transition: all 0.3s ease; }
.lightbox-leave-active { transition: all 0.2s ease; }
.lightbox-enter-from, .lightbox-leave-to { opacity: 0; }
</style>
