// pages/blog/[slug].vue
<template>
  <div class="min-h-screen pt-32 pb-20 transition-colors">
    <article v-if="post" class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Back Link -->
      <NuxtLink to="/about-me/my-info?section=blog"
        class="group inline-flex items-center gap-2 text-sm font-bold text-gray-400 transition-all uppercase tracking-widest mb-12">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 transition-transform"
          fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
        </svg>
        Back to Blog
      </NuxtLink>

      <!-- Hero -->
      <div class="rounded-3xl overflow-hidden mb-10 aspect-[16/9] flex items-center justify-center"
        :class="post.image ? '' : `bg-gradient-to-br ${post.gradient}`">
        <img v-if="post.image" :src="post.image" :alt="post.title"
          class="w-full h-full object-cover" />
        <span v-else class="text-9xl">{{ post.emoji }}</span>
      </div>

      <!-- Meta -->
      <div class="flex items-center gap-3 text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-widest mb-4">
        <span>{{ post.date }}</span>
        <span class="w-1 h-1 rounded-full bg-gray-300 dark:bg-gray-600"></span>
        <span>{{ post.category }}</span>
      </div>

      <!-- Title -->
      <h1 class="text-4xl md:text-5xl font-bold text-primary dark:text-white mb-8 leading-tight">
        {{ post.title }}
      </h1>

      <!-- Body -->
      <div class="prose prose-lg dark:prose-invert max-w-none">
        <p v-for="(paragraph, index) in paragraphs" :key="index"
          class="text-lg leading-relaxed text-gray-700 dark:text-gray-300 mb-6 whitespace-pre-line">
          {{ paragraph }}
        </p>
      </div>

      <!-- Tags -->
      <div class="flex flex-wrap gap-2 mt-12 pt-8 border-t border-gray-100 dark:border-gray-800">
        <span v-for="tag in post.tags" :key="tag"
          class="px-3 py-1.5 bg-gray-100 dark:bg-primary-light text-sm rounded-full text-gray-600 dark:text-gray-300">
          #{{ tag }}
        </span>
      </div>
    </article>

    <!-- Not Found -->
    <div v-else class="max-w-3xl mx-auto px-4 text-center py-32">
      <div class="text-6xl mb-4">🔍</div>
      <h1 class="text-3xl font-bold text-primary dark:text-white mb-2">Entry not found</h1>
      <p class="text-gray-500 dark:text-gray-400 mb-8">This blog entry doesn't exist.</p>
      <NuxtLink to="/about-me/my-info?section=blog"
        class="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-primary dark:bg-white text-white dark:text-primary font-semibold transition-all">
        Back to Blog
      </NuxtLink>
    </div>
  </div>
</template>

<script setup lang="ts">
const route = useRoute()
const { findBySlug } = useFeelings()

const post = computed(() => findBySlug(route.params.slug as string))

const paragraphs = computed(() => post.value?.body.split('\n\n') ?? [])

useHead({
  title: post.value ? `${post.value.title} | Blog` : 'Entry not found | Blog',
  meta: [
    { name: 'description', content: post.value?.body.slice(0, 150) ?? '' }
  ]
})
</script>

// app/blog/[slug]/page.tsx
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { Container } from '@/components/ui/Container'
import { PageHeader } from '@/components/ui/PageHeader'
import { Tag } from '@/components/ui/Tag'
import { useFeelings } from '@/lib/feelings'
import { BackToBlogLabel } from './BackToBlogLabel'

type Params = Promise<{ slug: string }>

const { posts, findBySlug } = useFeelings()

export const dynamicParams = false

export function generateStaticParams() {
  return posts.map(post => ({ slug: post.slug }))
}

export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> {
  const { slug } = await params
  const post = findBySlug(slug)
  return {
    title: post ? `${post.title} | Blog | Koeuk Dev` : 'Entry not found | Blog | Koeuk Dev',
    description: post?.body.slice(0, 150) ?? '',
  }
}

export default async function BlogEntryPage({ params }: { params: Params }) {
  const { slug } = await params
  const post = findBySlug(slug)
  if (!post) notFound()

  const paragraphs = post.body.split('\n\n')

  return (
    <Container>
      <PageHeader
        backHref="/about-me/my-info?section=blog"
        backLabel={<BackToBlogLabel />}
        title={post.title}
        subtitle={
          <span className="flex flex-wrap items-center gap-2 text-sm">
            <Tag>{post.category}</Tag>
            <span className="ml-1">{post.date}</span>
          </span>
        }
      />

      <div className="neo mb-10 flex aspect-[2/1] items-center justify-center overflow-hidden bg-main">
        {post.image ? (
          <img src={post.image} alt={post.title} className="h-full w-full object-cover" />
        ) : (
          <span className="text-8xl sm:text-9xl" aria-hidden="true">
            {post.emoji}
          </span>
        )}
      </div>

      <article className="article">
        {paragraphs.map((paragraph, index) => (
          <p key={index} className="whitespace-pre-line">
            {paragraph}
          </p>
        ))}
      </article>

      <div className="mt-12 flex flex-wrap gap-2 border-t-2 border-border pt-8">
        {post.tags.map(tag => (
          <Tag key={tag} className="px-3 py-1 text-sm">
            #{tag}
          </Tag>
        ))}
      </div>
    </Container>
  )
}
