// components/GitHub.vue
<template>
  <section id="github" ref="elementRef" class="section overflow-hidden">
    <div :class="{ 'section-visible': isVisible }">
      <h2 class="text-4xl md:text-5xl lg:text-6xl font-bold text-center mb-16 section-title title-shimmer">
        GitHub
      </h2>

      <div class="section-content max-w-7xl mx-auto px-4">
        <div class="p-6 sm:p-8 rounded-2xl bg-[#0d1117] border border-gray-700 text-white">
          <!-- Header -->
          <div class="flex items-center gap-3 mb-2">
            <span class="text-sm text-gray-400">koeuk / <strong class="text-white">README.md</strong></span>
          </div>

          <!-- Typing Title -->
          <div class="text-center py-6">
            <img
              src="https://readme-typing-svg.demolab.com?font=Fira+Code&size=32&weight=700&pause=1000&center=true&width=600&lines=Hello+There!+I'm+Koeuk+%F0%9F%99%8F&color=FFFFFF"
              alt="Hello There! I'm Koeuk"
              class="mx-auto"
            />
          </div>

          <hr class="border-gray-700 mb-6" />

          <!-- Welcome -->
          <div class="text-center mb-6">
            <span class="text-lg">Welcome to My Digital Space</span>
          </div>

          <!-- Experience Badge -->
          <div class="mb-6">
            <img src="https://img.shields.io/badge/Code_Experience-2023--2025-brightgreen?style=flat&logo=javascript" alt="Experience" />
          </div>

          <!-- Activity Graph -->
          <div class="mb-6">
            <img
              src="https://github-readme-activity-graph.vercel.app/graph?username=koeuk&theme=react-dark&hide_border=true&area=true"
              alt="Contribution Graph"
              class="w-full rounded-lg"
            />
          </div>

          <!-- Contribution Heatmap -->
          <div class="mb-8">
            <img
              src="https://ghchart.rshah.org/4ade80/koeuk"
              alt="GitHub Contribution Heatmap"
              class="w-full rounded-lg"
            />
          </div>

          <!-- Connect -->
          <h3 class="text-xl font-bold mb-4 border-b border-gray-700 pb-2">Connect With Me</h3>
          <div class="flex items-center justify-between">
            <div class="flex gap-4">
              <a href="https://github.com/koeuk" target="_blank" rel="noopener noreferrer"
                class="text-gray-400 hover:text-white transition-colors">
                <svg class="w-7 h-7" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
                </svg>
              </a>
              <a href="https://www.linkedin.com/in/koeuk-kos-130482299/" target="_blank" rel="noopener noreferrer"
                class="text-gray-400 hover:text-white transition-colors">
                <svg class="w-7 h-7" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
                </svg>
              </a>
              <a href="https://t.me/koeuk24" target="_blank" rel="noopener noreferrer"
                class="text-gray-400 hover:text-white transition-colors">
                <svg class="w-7 h-7" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z"/>
                </svg>
              </a>
              <a href="https://www.facebook.com/koeuk25/" target="_blank" rel="noopener noreferrer"
                class="text-gray-400 hover:text-white transition-colors">
                <svg class="w-7 h-7" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
                </svg>
              </a>
            </div>
            <NuxtLink to="/github"
              class="inline-flex items-center gap-2 px-5 py-2 rounded-full border border-gray-600 text-gray-300 hover:bg-white hover:text-[#0d1117] font-semibold transition-all hover:scale-105">
              View More
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
              </svg>
            </NuxtLink>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
const { isVisible, elementRef } = useScrollAnimation()
</script>

<style scoped>
.section-title,
.section-content {
  opacity: 0;
  filter: blur(10px);
  transform: translateY(50px) scale(0.95);
  transition: all 1.2s cubic-bezier(0.22, 1, 0.36, 1);
}

.section-visible .section-title {
  opacity: 1;
  filter: blur(0);
  transform: translateY(0) scale(1);
}

.section-visible .section-content {
  opacity: 1;
  filter: blur(0);
  transform: translateY(0) scale(1);
  transition-delay: 0.15s;
}
</style>

// components/about/GitHub.tsx
import { ArrowRight } from 'lucide-react'
import { SocialLinks } from '@/components/layout/SocialLinks'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'

// The typing banner sits on the orange `main` surface, so its text is black
// (the Nuxt site drew it white on GitHub's dark theme).
const TYPING_SVG =
  "https://readme-typing-svg.demolab.com?font=Fira+Code&size=32&weight=700&pause=1000&center=true&width=600&lines=Hello+There!+I'm+Koeuk+%F0%9F%99%8F&color=000000"

/** GitHub tab of My Info: a README-style card linking to the /github page. */
export function GitHub() {
  return (
    <section id="github">
      <h2 className="mb-8 font-heading text-xl sm:text-2xl">GitHub</h2>

      <Card className="p-0 sm:p-0">
        <p className="border-b-2 border-border px-4 py-3 text-sm sm:px-6">
          koeuk / <strong className="font-heading">README.md</strong>
        </p>

        <div className="p-4 sm:p-6">
          <div className="neo overflow-hidden bg-main px-3 py-5">
            <img src={TYPING_SVG} alt="Hello There! I'm Koeuk" className="mx-auto w-full max-w-[600px]" />
          </div>

          <p className="mt-6 text-center font-heading text-lg">Welcome to My Digital Space</p>

          <img
            src="https://img.shields.io/badge/Code_Experience-2023--2025-brightgreen?style=flat&logo=javascript"
            alt="Experience"
            className="mt-6"
          />

          <div className="neo mt-6 overflow-hidden bg-bw">
            <img
              src="https://github-readme-activity-graph.vercel.app/graph?username=koeuk&theme=react-dark&hide_border=true&area=true"
              alt="Contribution Graph"
              className="block w-full"
              loading="lazy"
            />
          </div>

          <div className="neo mt-6 overflow-hidden bg-bw p-3">
            <img
              src="https://ghchart.rshah.org/4ade80/koeuk"
              alt="GitHub Contribution Heatmap"
              className="block w-full"
              loading="lazy"
            />
          </div>

          <h3 className="mt-10 border-b-2 border-border pb-2 font-heading text-lg sm:text-xl">Connect With Me</h3>
          <div className="mt-6 flex flex-wrap items-center justify-between gap-6">
            <SocialLinks className="gap-6" />
            <Button href="/github" variant="main">
              View More
              <ArrowRight className="h-4 w-4" aria-hidden />
            </Button>
          </div>
        </div>
      </Card>
    </section>
  )
}
