// app/read-more/tailwind-responsive-layouts/page.tsx
import { Article } from '@/components/ui/Article'

export const metadata = {
  title: 'Building Responsive Layouts with Tailwind CSS | Koeuk Dev',
  description: 'Building responsive layouts with Tailwind CSS.',
}

export default function TailwindResponsiveLayoutsPage() {
  return (
    <Article
      title="Building Responsive Layouts with Tailwind CSS"
      date="Jan 10, 2026"
      tags={['Tailwind', 'CSS']}
      backHref="/about-me/my-info?section=rean"
    >
      <p>Content coming soon...</p>
    </Article>
  )
}

// pages/read-more/tailwind-responsive-layouts.vue
<template>
  <div class="min-h-screen bg-white dark:bg-primary pt-20">
    <div class="max-w-4xl mx-auto px-6 py-12">
      <NuxtLink to="/about-me/my-info?section=rean" class="inline-flex items-center gap-2 text-gray-500 dark:text-gray-400 transition-colors mb-8">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"/></svg>
        {{ t('readMore.back') }}
      </NuxtLink>

      <div class="mb-12">
        <div class="flex gap-2 mb-4">
          <span class="px-3 py-1 bg-teal-100 dark:bg-teal-900/30 text-teal-600 dark:text-teal-400 text-xs rounded-full font-medium">Tailwind</span>
          <span class="px-3 py-1 bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 text-xs rounded-full font-medium">CSS</span>
        </div>
        <h1 class="text-3xl md:text-4xl lg:text-5xl font-bold text-primary dark:text-white mb-4">
          Building Responsive Layouts with Tailwind CSS
        </h1>
        <p class="text-gray-500 dark:text-gray-400">Jan 10, 2026</p>
      </div>

      <article class="prose-content">
        <p class="text-lg text-gray-600 dark:text-gray-300 leading-relaxed">
          Content coming soon...
        </p>
      </article>
    </div>
  </div>
</template>

<script setup lang="ts">
const { t } = useI18n()
useHead({ title: 'Building Responsive Layouts with Tailwind CSS - Koeuk Dev' })
</script>
